# Run CI for R using https://eddelbuettel.github.io/r-ci/

name: ci

on:
  push:
  pull_request:

jobs:
  ci:
    strategy:
      matrix:
        include:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

    runs-on: ${{ matrix.os }}

    env:
      _R_CHECK_FORCE_SUGGESTS_: "false"
      _R_CHECK_TESTS_NLINES_: 0
      NOT_CRAN: true
      R_NOT_CRAN: true
      R_GH: true
      GITHUB_PAT: ${{ secrets.GITHUB_PAT}}

    steps:
      - uses: actions/checkout@v3

      - name: Get Script
        run: curl -OLs https://eddelbuettel.github.io/r-ci/run.sh && chmod 0755 run.sh

      - name: Bootstrap
        run: ./run.sh bootstrap

      - name: png (for svglite)
        run: sudo apt update -qq && sudo apt install --yes --no-install-recommends libpng-dev
        
      - name: svglite from source
        run: Rscript -e "bspm::disable();install.packages('svglite', from = 'source');bspm::enable()"

      - name: Dependencies
        run: ./run.sh install_all
          
      - name: Pandoc binary
        run: Rscript -e "pandoc::pandoc_install()"

      - name: Test
        run: ./run.sh run_tests

      - name: Coverage
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: ./run.sh coverage
